# Generated by Django 5.0.4 on 2024-04-11 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sellerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('owner_name', models.CharField(max_length=250)),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('zone', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=500)),
                ('nid', models.IntegerField()),
            ],
        ),
    ]
