# Generated by Django 5.0.4 on 2024-04-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerAccount', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
