# Generated by Django 5.0.4 on 2024-04-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerAccount', '0002_selleraccount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleraccount',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='selleraccount',
            name='password',
            field=models.CharField(help_text='Use \'[algo]$[salt]$[hexdigest]\' or use the <a href="password/">change password form</a>.', max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='selleraccount',
            name='phone',
            field=models.IntegerField(unique=True),
        ),
    ]
