# Generated by Django 5.0.4 on 2024-04-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerAccount', '0003_alter_selleraccount_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selleraccount',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
