# Generated by Django 5.0.4 on 2024-04-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellerAccount', '0009_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='selleraccount',
            name='slug',
            field=models.SlugField(max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='otptoken',
            name='otp_code',
            field=models.CharField(default='77156b', max_length=10),
        ),
    ]
