# Generated by Django 5.0.4 on 2024-04-21 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellerAccount', '0034_alter_otptoken_otp_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='otpToken',
        ),
    ]
