# Generated by Django 5.0.4 on 2024-04-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='catgory_img',
            field=models.FileField(blank=True, upload_to='photos/categories'),
        ),
    ]
