# Generated by Django 5.0.4 on 2024-04-10 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_billingdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
