# Generated by Django 5.0.4 on 2024-04-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_remove_billingdetails_cart_item_and_more'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingdetails',
            name='product',
        ),
        migrations.AddField(
            model_name='billingdetails',
            name='product',
            field=models.ManyToManyField(null=True, to='product.product'),
        ),
    ]
