# Generated by Django 5.0.4 on 2024-04-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_remove_billingdetails_product_billingdetails_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='quantity',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
