# Generated by Django 5.0.4 on 2024-04-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_billingdetails_quantity'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingdetails',
            name='product',
            field=models.ManyToManyField(null=True, related_name='products', to='product.product'),
        ),
    ]
