# Generated by Django 5.0.4 on 2024-04-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_firstordercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='firstordercoupon',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
