# Generated by Django 5.0.4 on 2024-04-21 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_alter_billingdetails_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingdetails',
            name='order_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
